#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = hyprlock
exec-once=waybar
exec-once=swaync
exec-once=hyprpaper
exec-once=wal -R & firefox
exec-once=pidof -x low_battery.sh || $HOME/.config/hypr/scripts/low_battery.sh
exec-once= wlsunset -S 07:00 -s 20:00 -g 1.25

# Start Apps in specified workspaces
exec-once=[workspace special:magic silent;] /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/ca05d2f153da6573c1c00b377d649797983cc697eae9342aaefa8d57565a04e7/files/discord/Discord & spotify-launcher
exec-once=[workspace 1 silent;] $terminal
exec-once=[workspace 2 silent;] nvim
exec-once=[workspace 3 silent;] firefox
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
