github.com:
    users:
        BobyWoby:
            oauth_token: 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
            git_protocol: https
    git_protocol: https
    user: BobyWoby
    oauth_token: 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
