github.com:
    users:
        BobyWoby:
            oauth_token: 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
            git_protocol: https
    git_protocol: ssh
    user: BobyWoby
    oauth_token: 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
