github.com:
    users:
        BobyWoby:
            oauth_token: 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
    git_protocol: https
    user: BobyWoby
    oauth_token: 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
